apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: edu-trusting-darwin
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: spsvk/django_app:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "manage.py",  "migrate", "--no-input"]
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres
                key: url
          - name: SECRET_KEY
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: secret-key
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: debug
          - name: ALLOWED_HOSTS
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: allowed-hosts
