apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: edu-trusting-darwin
spec:
  selector:
    app: django-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30371
      protocol: TCP
  type: NodePort
