apiVersion: batch/v1
kind: CronJob
metadata:
  name: clearsessions
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: clearsession
            image: spsvk/django_app:latest
            command: ["python", "manage.py",  "clearsessions"]
            envFrom:
              - configMapRef:
                  name: django-config
        restartPolicy: OnFailure