apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django_app
  template:
    metadata:
      labels:
        app: django_app
    spec:
      containers:
        - name: django
          image: spsvk/django_app:latest
          envFrom:
            - configMapRef:
                name: django-config
          imagePullPolicy: Never
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: django-app
  labels:
    app.kubernetes.io/name: deployment
spec:
  selector:
    app: django
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
  